
hide_window_decorations yes
window_padding_width 10
override_redirect yes
background_opacity 0.9
background_blur 10
inactive_text_alpha 0.8
shell tmux new -A -s main
font_family JetBrainsMono Nerd Font

